#!/bin/bash

MAJOR=$1
MINOR=$2


# cabal update
if [ -d "nagios-check" ]; then
        pushd nagios-check
        git pull
        popd
else
        git clone https://github.com/fractalcat/nagios-check
fi

mkdir -p artefacts

for f in check-*; do
    if [[ -d "$f" ]]; then
        pushd "$f"

        cabal sandbox init
        cabal sandbox add-source ../nagios-check/

        cabal install

        cp .cabal-sandbox/bin/* ../artefacts
        popd
    fi
done

# Build an RPM package.
sudo yum install rpm-build rpmdevtools
rpmdev-setuptree

tar czf rpm/SOURCES/haskell-nagios-checks-bin.tar.gz artefacts/

pushd rpm
rpmbuild -ba ../pkg/centos/haskell-nagios-checks.spec
